project = Aviation Pollution Compliance
output = Aviation Pollution Compliance/output
dep = Aviation_Pollution_Compliance
xom-classpath = aviation-compliance-xom/aviation-compliance-xom.jar

# Made with Bob
